name: "🐛 Bug Report"
description: Create a new bug report.
#title: ""
labels: [
  "triage/new 🆕",
  "kind/bug 🐛",
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Describe precisely what's happening.
      placeholder: Short and explicit description of your incident
    validations:
      required: true
  - type: checkboxes
    id: applications
    attributes:
      label: "Application(s) impacted"
      description: Which applications/components are impacted ?
      options:
        - label: Dashboard Merchant
        - label: PoS
        - label: Admin Cresh
        - label: Payflow
        - label: Modules CMS / SDK PHP (details)
  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      description: Describe what would be the right behavior.
      placeholder: Clear and concise description
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
        ## Sales / CSM
  - type: dropdown
    id: sales_representative
    attributes:
      label: "Sales Representative"
      description: Who is following the issue with the merchant ?
      multiple: false
      options:
        - Bruno
        - Jérémy
        - Thomas
    validations:
      required: false
  - type: dropdown
    id: emergency
    attributes:
      label: "Emergency Level"
      description: How much impactful is the bug for the production ?
      multiple: false
      options:
        - 1/ Critical (immediate response, prod is broken)
        - 2/ Problematic (can be delayed for a few days)
        - 3/ Annoying (can live with it for a while)
        - 4/ Unnoticed (should probably be fixed at some point)
    validations:
      required: true
