name: "🌟 Feature Request"
description: Suggest some changes or new feature that could improve our products.
#title: ""
labels: [
  "triage/new 🆕",
  "kind/request 🌟",
]
body:
  - type: checkboxes
    id: applications
    attributes:
      label: "Application(s)"
      description: Which application(s)/component(s) are concerned ?
      options:
        - label: Dashboard Merchant
        - label: PoS
        - label: Admin Cresh
        - label: Payflow
        - label: Modules CMS / SDK PHP (details)
    validations:
      required: true
  - type: textarea
    id: current_context
    attributes:
      label: "Current Context"
      description: Context about the current implementation.
      placeholder: Describe in a few lines how are things currently.
    validations:
      required: true
  - type: textarea
    id: suggested_implementation
    attributes:
      label: "Suggested Implementation"
      description: Detail the implementation suggested to resolve this story.
      placeholder: |
        Describe in details what is expected to be achieve by this story.
        What changes in the experience or the functionality will we do ?
    validations:
      required: true
  - type: dropdown
    id: impact
    attributes:
      label: "Business Impact"
      description: How much impactful for business this feature would be ?
      multiple: false
      options:
        - 1/ Game changer
        - 2/ Long awaited
        - 3/ Useful
        - 4/ Unnoticeable
    validations:
      required: true
